theme: jekyll-theme-architect
title: Codon Stream
description: Homepage
paginate: 5
plugins:
- jekyll-paginate
kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3
