theme: jekyll-theme-architect
title: Codon Stream
description: Homepage
pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
permalink: /:year/:month/:title.html
gems:
  - jekyll-paginate-v2
kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3
